version: '3.2'

networks:
  default:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.35.0.0/16
volumes:
  # persist the database
  yii2advanced_db:
  composer_cache:

services:
  yii:
    build:
      context: .
      dockerfile: docker/yii.Dockerfile
    volumes:
      - ./:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - composer_cache:/home/www/.composer
    environment:
      TZ: "Europe/Moscow"
      MODE: "development"
    networks:
      - default
  nginx:
    image: nginx:1.17.8
    #ports:
    # - '80:80'
    # - '443:443'
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/yii2advanced
      - ./docker/nginx/configs/local.yii2advanced.ru.conf:/etc/nginx/conf.d/local.yii2advanced.ru.conf
      - ./docker/nginx/configs/local.admin.yii2advanced.ru.conf:/etc/nginx/conf.d/local.admin.yii2advanced.ru.conf
    networks:
      default:
        #ipv4_address: 172.35.0.10
    depends_on:
      - yii
  db:
    image: postgres:10.19
    restart: unless-stopped
    environment:
      - POSTGRES_DB=yii2advanced
      - POSTGRES_USER=yii2advanced
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      #- ./:/app
      - yii2advanced_db:/var/lib/postgresql/data
    networks:
      - default
